package ui;

import service.PretService;
import entities.Prets;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class AficherInfoPret extends javax.swing.JInternalFrame {

    private PretService pretService = new PretService();
    private DefaultTableModel model;

    public AficherInfoPret() {
        initComponents();

        model = (DefaultTableModel) jTable1.getModel();

        bnEliminer.addActionListener(e -> supprimerPret());
        bnAficher.addActionListener(e -> chargerPrets());
        this.setSize(700, 700);
    }

    private void chargerPrets() {
        try {
            Integer idPret = null;
            Integer idClient = null;
            
            // Vérifier si les champs de texte existent et ne sont pas vides
            if (txtIdPret != null && !txtIdPret.getText().trim().isEmpty()) {
                idPret = Integer.parseInt(txtIdPret.getText().trim());
            }
            
            if (txtIdClient != null && !txtIdClient.getText().trim().isEmpty()) {
                idClient = Integer.parseInt(txtIdClient.getText().trim());
            }
            
            // Utiliser le service directement
            List<Prets> liste = pretService.rechercherPrets(idPret, idClient);
            
            // Vider le tableau
            model.setRowCount(0);
            
            // Remplir le tableau avec les résultats
            for (Prets p : liste) {
                model.addRow(new Object[]{
                    p.getId_pret(),
                    p.getId_client(),
                    p.getMontant_total(),
                    p.getDate_pret(),
                    p.getTaux_interet()
                });
            }
            
            // Afficher un message si aucun résultat
            if (liste.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Aucun prêt trouvé",
                        "Information",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez entrer des nombres valides",
                    "Erreur de format",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erreur : " + ex.getMessage(),
                    "Erreur",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void supprimerPret() {
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez sélectionner un prêt",
                    "Attention",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idPret = (int) model.getValueAt(row, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Confirmer la suppression du prêt N°" + idPret + " ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                pretService.supprimerPret(idPret);
                JOptionPane.showMessageDialog(this,
                        "Prêt supprimé avec succès",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE);
                chargerPrets(); // Rafraîchir la liste
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Erreur lors de la suppression : " + ex.getMessage(),
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }
    
    // Cette méthode n'est pas nécessaire car vous utilisez pretService directement
    // private void rechercherPrets(Integer idPret, Integer idClient) { ... }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idPretLable = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        txtIdPret = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bnAficher = new javax.swing.JButton();
        bnEliminer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        idLabel.setText("id client :");

        idPretLable.setText("id_pret : ");

        txtIdClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPretLable)
                .addGap(30, 30, 30)
                .addComponent(txtIdPret, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(idLabel)
                .addGap(39, 39, 39)
                .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idPretLable)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        bnAficher.setText("Afficher");
        bnAficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAficherActionPerformed(evt);
            }
        });

        bnEliminer.setText("eliminer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bnAficher)
                    .addComponent(bnEliminer))
                .addGap(113, 113, 113))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bnAficher)
                .addGap(18, 18, 18)
                .addComponent(bnEliminer)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_pret", "id_client", "montant", "date_pret", "taux_interet"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClientActionPerformed

    private void bnAficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAficherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnAficherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAficher;
    private javax.swing.JButton bnEliminer;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idPretLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtIdPret;
    // End of variables declaration//GEN-END:variables
}
